var mongoose = require("mongoose");

var ItemSchema = new mongoose.Schema({
  type: String,
  img: String,
  baked_img: String,
  sc_baked_img: String,
  name: String,
  rarity: String,
  team: String,
  team_short_name: String,
  ovr: Number,
  series: String,
  series_texture_name: String,
  series_year: Number,
  display_position: String,
  display_secondary_positions: String,
  jersey_number: String,
  age: Number,
  bat_hand: String,
  throw_hand: String,
  weight: String,
  height: String,
  born: String,
  is_hitter: Boolean,
  stamina: Number,
  pitching_clutch: Number,
  hits_per_bf: Number,
  k_per_bf: Number,
  bb_per_bf: Number,
  hr_per_bf: Number,
  pitch_velocity: Number,
  pitch_control: Number,
  pitch_movement: Number,
  contact_left: Number,
  contact_right: Number,
  power_left: Number,
  power_right: Number,
  plate_vision: Number,
  plate_discipline: Number,
  batting_clutch: Number,
  bunting_ability: Number,
  drag_bunting_ability: Number,
  hitting_durability: Number,
  fielding_durability: Number,
  fielding_ability: Number,
  arm_strength: Number,
  arm_accuracy: Number,
  reaction_time: Number,
  blocking: Number,
  speed: Number,
  baserunning_ability: Number,
  baserunning_aggression: Number,
  hit_rank_image: String,
  fielding_rank_image: String,
  pitches: [{ type: mongoose.Schema.Types.ObjectId, ref: "Pitch" }],
  quirks: [{ type: mongoose.Schema.Types.ObjectId, ref: "Quirk" }],
  is_sellable: Boolean,
  has_augment: Boolean,
  augment_text: String,
  augment_end_date: String,
  has_matchup: Boolean,
  stars: String,
  trend: String,
  new_rank: Number,
  has_rank_change: Boolean,
  event: Boolean,
  set_name: String,
  is_live_set: Boolean,
  ui_anim_index: Number,
});

module.exports = mongoose.model("Item", ItemSchema);
